webpackJsonp([9],{

/***/ 451:
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "单个连续模块垂直排列，显示当前的内容、状态和可进行的操作。eg：联系人列表。"
    ],
    [
      "h2",
      "何时使用"
    ],
    [
      "ul",
      [
        "li",
        [
          "p",
          "一般由主要信息、主要操作、次要信息、次要操作组成。"
        ]
      ],
      [
        "li",
        [
          "p",
          "主要信息和主要操作放在列表的左边，次要信息和次要操作放在列表的右边。"
        ]
      ]
    ]
  ],
  "meta": {
    "category": "Components",
    "type": "Data Display",
    "title": "List",
    "subtitle": "列表",
    "filename": "components/list/index.zh-CN.md"
  },
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "h3",
      "List"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "属性"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "title"
          ],
          [
            "td",
            "标题"
          ],
          [
            "td",
            "String"
          ],
          [
            "td",
            "无"
          ]
        ],
        [
          "tr",
          [
            "td",
            "extra"
          ],
          [
            "td",
            "右边内容"
          ],
          [
            "td",
            "String/React.Element"
          ],
          [
            "td",
            "无"
          ]
        ]
      ]
    ],
    [
      "h3",
      "List.Item"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "属性"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "title"
          ],
          [
            "td",
            "标题"
          ],
          [
            "td",
            "String"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "brief"
          ],
          [
            "td",
            "子标题"
          ],
          [
            "td",
            "String"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "extra"
          ],
          [
            "td",
            "标题辅助内容，如",
            [
              "code",
              "Icon"
            ]
          ],
          [
            "td",
            "React.Element"
          ],
          [
            "td",
            "无"
          ]
        ],
        [
          "tr",
          [
            "td",
            "arrow"
          ],
          [
            "td",
            "箭头方向",
            [
              "code",
              "left"
            ],
            ",",
            [
              "code",
              "right"
            ],
            ",",
            [
              "code",
              "up"
            ],
            ",",
            [
              "code",
              "down"
            ],
            ",",
            [
              "code",
              "empty"
            ],
            ", ",
            [
              "code",
              "\"\""
            ]
          ],
          [
            "td",
            "String"
          ],
          [
            "td",
            [
              "code",
              "right"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "align"
          ],
          [
            "td",
            "自定义内容时，内容位置，可选",
            [
              "code",
              "left"
            ],
            ", ",
            [
              "code",
              "right"
            ],
            ", ",
            [
              "code",
              "center"
            ]
          ],
          [
            "td",
            "String"
          ],
          [
            "td",
            [
              "code",
              "right"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "onClick"
          ],
          [
            "td",
            "点击事件的回调函数"
          ],
          [
            "td",
            "(): void"
          ],
          [
            "td",
            "无"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

});
//# sourceMappingURL=index.zh-CN.md.js.map