sudo: false

language: node_js

node_js:
  - 8

notifications:
  email:
    - tdida@qq.com

matrix:
  fast_finish: true
  include:
    - env: TEST_TYPE=lint
    - env: TEST_TYPE=test:dist
    - env: TEST_TYPE=test:lib
    - env: TEST_TYPE=test:es
    - env: TEST_TYPE=test:dom

script:
  - scripts/travis-script.sh
